# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mactop < Formula
  desc "Apple Silicon Monitor Top written in Go Lang"
  homepage "https://github.com/metaspartan/mactop"
  version "2.1.6"

  depends_on "macos"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/metaspartan/mactop/releases/download/v2.1.6/mactop_2.1.6_darwin_arm64.tar.gz"
    sha256 "b8edd49c5f8a469ec5ff5e4ac5fb3cd4b2e735e8f3496fb62ff2cd52eacb0456"

    define_method(:install) do
      bin.install "mactop"
    end
  end

  def caveats
    <<~EOS
      mactop requires macOS 12+, and runs exclusively on Apple Silicon.

      To run mactop as a background service:
        brew services start mactop

      To view service error logs:
        brew services logs mactop

      Prometheus metrics will be available at:
        http://localhost:9101/metrics

      To change the Prometheus port:
        1. brew services stop mactop
        2. brew services edit mactop
        3. Change 9101 to your desired port
        4. brew services start mactop

      Or run manually with a custom port:
        mactop -p <PORT> --headless
    EOS
  end

  service do
    run [opt_bin/"mactop", "-p", "9101", "--headless"]
    keep_alive true
    log_path var/"log/mactop.log"
    error_log_path var/"log/mactop.error.log"
    process_type :background
    nice 10
  end
end
